name: Run tests

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
      - "*.in"
      - "*.txt"

  pull_request:
    branches: [main]
    paths-ignore:
      - "*.md"
      - "*.in"
      - "*.txt"

jobs:
  test:
    env:
      plugin_name: "otio_openassetio"

    name: Test
    strategy:
      matrix:
        python-version: [3.9, ]

    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Clone OpenAssetIO
        uses: actions/checkout@v2
        with:
          repository: TheFoundryVisionmongers/OpenAssetIO
          ref: feature/181-coreCppBuild
          path: dependencies/OpenAssetIO

      # Don't cache this as python does some system package installs
      # that won't be cached and it then breaks on the next run.
      - name: Build OpenAssetIO
        run: |
          pip install conan==1.45.0 cmake==3.21 ninja==1.10.2.3 cpplint==1.5.5
          conan profile new default --detect --force
          conan profile update settings.compiler.libcxx=libstdc++ default
          conan install --install-folder ~/.conan --build=missing dependencies/OpenAssetIO/resources/build
          cmake -S dependencies/OpenAssetIO -B build  \
            --toolchain ~/.conan/conan_paths.cmake \
            --install-prefix $GITHUB_WORKSPACE/dist
          cmake --build build --target openassetio-python-py-install

      - name: Clone OpenAssetIO-MediaCreation
        uses: actions/checkout@v2
        with:
          repository: TheFoundryVisionmongers/OpenAssetIO-MediaCreation
          path: dependencies/OpenAssetIO-MediaCreation

      - name: Install dependencies
        run: |
          . dist/bin/activate
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov OpenTimelineIO==0.13.0
          pip install dependencies/OpenAssetIO-MediaCreation

      - name: Install Plugin
        run: |
          . dist/bin/activate
          pip install -e .

      - name: Lint with flake8
        run: |
          . dist/bin/activate
          flake8 --show-source --statistics otio_openassetio tests

      - name: Test with pytest
        run: |
          . dist/bin/activate
          pytest tests
        env:
          OPENASSETIO_PLUGIN_PATH: dependencies/OpenAssetIO/resources/examples/manager/BasicAssetLibrary/plugin
        shell: bash
